---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.10.9
  always_update_cookbooks: true

verifier:
  name: inspec
  chef_license: accept-no-persist

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[UberAppProject::default]
    verifier:
      inspec_tests:
        - test/integration/default
      chef_license: accept-no-persist
    attributes:
