driver:
  name: ec2
  region: eu-west-1
  require_chef_omnibus: true
  intance_type: t2.micro
  associate_public_io: true
  chef_license: accept-no-persist
  product_name: chef
  product_version: 13.3.42
transport:
  username: ubuntu


verifier:
  name: inspec
  chef_license: accept-no-persist

platforms:
  - name: ubuntu-18.04
    driver:
      box: ubuntu/xenial64

suites:
  - name: default
    run_list:
      - recipe[UberAppProject::default]
    verifier:
      inspec_tests:
        - test/integration/default
      chef_license: accept-no-persist
    attributes:
